Create landing product page
Computational-Puzzles/ComputationalPuzzles pull request #36
Opened 2021-10-27 21:44 UTC by MtheDV

- Create product components
   - Create Header component
   - Create Footer component
   - Create Landing component
 - Make Button components EM based, so they can change sizes
 - Add 'flat' option to button
 - Add mobile/tablet/desktop breakpoints

Closes #35

2021-11-01 10:15 UTC, Opeyem1a requested changes

2021-11-01 10:15 UTC, Opeyem1a commented on src/components/Global/Button/index.tsx
>    if (type === 'outline') return styles.arrowOutline;
we could use `||` to make these 1 line

2021-11-01 10:15 UTC, Opeyem1a commented on src/components/Product/Product.module.scss
> +@import '../../styles/abstracts/variables';
I reckon this file should go in `styles/pages/` - the goal is that non-component specific styling goes there

2021-11-01 10:15 UTC, Opeyem1a commented on src/pages/index.tsx
> +      <Landing />
Maybe `<LandingContent />` for now and we can revisit this later (?)

2021-11-01 10:15 UTC, Opeyem1a commented on src/components/Global/Button/Button.module.scss
> +  padding: 0.3em 0.3em 0.3em 0.75em;
I'm not sure what the `('small', 'medium', 'large')` idea means, but are you saying that using `em`, if the font size in a div was big and I wanted a button inside that div, I'd have to style that button to have `font-size: 1rem;` to make it look normal?

2021-11-04 00:05 UTC, MtheDV commented on src/components/Global/Button/Button.module.scss
> +  padding: 0.3em 0.3em 0.3em 0.75em;
that is what it would be yes

2021-11-04 00:06 UTC, MtheDV commented on src/components/Global/Button/Button.module.scss
> +  padding: 0.3em 0.3em 0.3em 0.75em;
by providing the 'small', 'medium', 'large' sizing options as props we can avoid this hassle and just have that functionality within the button component

2021-11-04 18:58 UTC, Opeyem1a approved these changes

2021-11-04 18:58 UTC, merged